export const CLIENT_ADMIN = "CLIENT_ADMIN";
export const CLIENT_USER = "CLIENT_USER";
export const COMPANY_ADMIN = "COMPANY_ADMIN";
export const COMPANY_DEVELOPER = "COMPANY_DEVELOPER";

export const ADVANCE_PAYMENT = "ADVANCE_PAYMENT";
export const FINAL_PAYMENT = "FINAL_PAYMENT";
export const REQUIREMENT_PAYMENT = "REQUIREMENT_PAYMENT";
export const BUG_PAYMENT = "BUG_PAYMENT";